version: '4.3'

services:
  db1:
    image: mysql:8.0
    container_name: mysql-mscustomer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mscustomer_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"

  db2:
    image: mysql:8.0
    container_name: mysql-mspayment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mspayment_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"

  db3:
    image: mysql:8.0
    container_name: mysql-mscalculate
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mscalculate_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"

  db4:
    image: mysql:8.0
    container_name: mysql-msfilestorage
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: msfilestorage_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"

