version: '4.3'

services:
  db1:
    image: mysql:8.0
    container_name: mysql-mscustomer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mscustomer_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - banco-network

  db2:
    image: mysql:8.0
    container_name: mysql-mspayment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mspayment_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    networks:
      - banco-network

  db3:
    image: mysql:8.0
    container_name: mysql-mscalculate
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mscalculate_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    networks:
      - banco-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - banco-network

networks:
  banco-network:
    driver: bridge

