
spring:
  application:
    name: mspayment
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082

mq:
  queues:
    payment: payment